name: Deploy API to VM Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -t siuit/email-tracking-server:${{ github.sha }} -t siuit/email-tracking-server:latest -f email-tracking-server/Dockerfile email-tracking-server
          docker push siuit/email-tracking-server:${{ github.sha }}
          docker push siuit/email-tracking-server:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker ps -a

            sudo docker stop email-tracking-server || true
            sudo docker rm -f email-tracking-server || true

            sudo docker pull siuit/email-tracking-server:latest
            sudo docker run -d -p 3001:3001 --restart unless-stopped --name email-tracking-server \
              -e "DB_HOST=${{secrets.DB_HOST}}" \
              -e "DB_NAME=${{secrets.DB_NAME}}" \
              -e "DB_PASS=${{secrets.DB_PASS}}" \
              -e "DB_PORT=${{secrets.DB_PORT}}" \
              -e "DB_USER=${{secrets.DB_USER}}" \
              -e "DB_SSL=${{secrets.DB_SSL}}" \
              -e "GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" \
              -e "GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}" \
              -e "GOOGLE_REDIRECT_URI=${{secrets.GOOGLE_REDIRECT_URI}}" \
              siuit/email-tracking-server:latest
            sudo docker image prune -f
