name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t siuit/email-tracking-server:${{github.sha}} .
          docker push siuit/email-tracking-server:${{github.sha}}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull siuit/email-tracking-server:${{github.sha}}
            docker ps -a
            docker stop email-tracking-server || true
            docker rm -f email-tracking-server || true
            docker run -d -p 3001:3001 --restart unless-stopped --name email-tracking-server siuit/email-tracking-server:${{github.sha}}
            docker image prune -f
